### PR TITLE
Fix card show more/less toggle button to render an appropriate number of cards in groups of 3

### LINKED ISSUE #244: Should show full "rows" of cards in typical desktop view (currently first row show 3 cards, second is a single card)
Previously we had 4 cards across, and no second row. We should revert to that layout or something equally sensible.

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary
The number of cards that rendered within a collection in the devhub would sometimes show up in a less than ideal fashion. There maybe singled out cards that would wrap to a new row. This PR forces all cards to show up in atleast a group of three (if numCard >= 3);

## Notable Changes 
- added a helper to calculate the ideal card limit for toggling
- added unit tests for said helper

Fixes #244

### CODE REVIEW

**Comment by patricksimonian** [comment]
@lukegonis you may be interested in the logic that was used to achieve how the cards render. It's all math! Gota love it 😸

File: app-web/src/components/Cards/Cards.js [hunk 1]
```diff
@@ -92,17 +106,27 @@ const Cards = ({ topic, sourcePath, cards }) => {
       </Link>
     );
   if (cardComponents.length > 0) {
+    // find the ideal large screen limit based on number of cards, and cards rendering per row
+    const CARDS_PER_ROW = 3; // ideally in a true grid system we would have a more concrete styling
```
Comment (jleach) [inline app-web/src/components/Cards/Cards.js]: I might try constants like this in a `constants.js` file.

Comment (patricksimonian) [reply app-web/src/components/Cards/Cards.js]: good point, changed
