### PR TITLE
Bug/search feedback

### LINKED ISSUE #469: If search returns no results it shows the no resources message
**Describe the bug**
Goto search and type 'asdfljasdf' (you get the point)

instead of getting the 'no search results message' we get a no resources found which is not cancelable.

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary
Quick Summary Here
Added some improvements to search to prevent wierd issues like no search results messages being not shown.

Fixes #469 

/bot-ignore-length

### CODE REVIEW

File: app-web/src/pages/index.js [hunk 1]
```diff
@@ -49,17 +52,20 @@ export class Index extends PureComponent {
   }
 
   componentDidUpdate() {
+    console.log('update called!');
```
Comment (ShellyXueHan) [inline app-web/src/pages/index.js]: remove console log

File: app-web/src/templates/resourceType.js [hunk 2]
```diff
@@ -106,11 +97,11 @@ export class ResourceType extends PureComponent {
             subtitle={RESOURCE_TYPE_PAGES[pageContext.resourceType].header.subtitle.defaultMessage}
           />
           <PageContainer>
-            {resources.length > 0 ? (
+            {resources.length > 0 || searchResultsEmpty ? (
```
Comment (ShellyXueHan) [inline app-web/src/templates/resourceType.js]: discuss?

File: app-web/src/store/selectors/resources.js [hunk 3]
```diff
@@ -114,3 +114,11 @@ export const selectResourcesReducerLoading = createSelector(
   resourcesSelector,
   resources => resources.loading,
 );
+
+export const selectSearchResultsExist = createSelector(
+  selectSearchResultsLength,
+  (searchResultsLength, searchWordLength, query) => {
+    console.log(query, searchResultsLength, searchResultsLength > 0);
```
Comment (ShellyXueHan) [inline app-web/src/store/selectors/resources.js]: remove it?
