### PR TITLE
Chore Tasks for UI/UX bugs

### LINKED ISSUE #1180: Event brite events no longer showing their dates and location
**Describe the bug**
The event brite event cards used to show event information like dates and location. This appears not to be the case anymore ?

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary
I'm Addressing various small issues identified in our issue backlog. Things that were 5-10minute tasks.

Fixes #1180 #1181 #1176 #1174

### CODE REVIEW

File: app-web/src/templates/events.js [hunk 1]
```diff
@@ -95,24 +96,28 @@ export const EventsPage = ({ data: { allEventbriteEvents, allTopicRegistryJson }
...
+  let currentEventsMeetUpsAndCards = currentEvents
+    .sort((a, b) => b.start.daysFromNow - a.start.daysFromNow)
+    .concat(communityEventCards);
 
   // community and event cards to carry a light reference to eventbrite cards, essentially titles and node fields
   // these need to be removed
 
   currentEventsMeetUpsAndCards = uniqBy(currentEventsMeetUpsAndCards, 'id');
 
+  console.log(currentEventsMeetUpsAndCards);
```
Comment (w8896699) [inline app-web/src/templates/events.js]: console.log

File: app-web/gatsby/resolvers/devhubTopic.js [hunk 2]
```diff
@@ -59,21 +59,19 @@ const resolveDevhubTopicConnections = (source, args, context) => {
       }));
 
     // event nodes are only connected if they occur in the future
-    const eventNodes = eventbriteNodes
-      .concat(meetupNodes)
-      .filter(n => nodeBelongsToTopic(source.name, n) && n.fields.daysFromNow >= 0)
-      .map(n => ({ fields: { ...n.fields }, id: n.id, path: n.fields.pagePaths[0] }));
+    // const eventNodes = eventbriteNodes
+    //   .concat(meetupNodes)
```
Comment (w8896699) [inline app-web/gatsby/resolvers/devhubTopic.js]: do we want to remove those commented out code?
