### PR TITLE
Fix filters not resetting on new searches

### LINKED ISSUE #1245: Filtering on homepage does not reset on a new search
**Describe the bug**
When searching you can filter the results by their resource type. if you do another search after clicking the filters they do not reset

**To Reproduce**
1. Go to 'home page'
2. search openshift
3. click the documentation pill
4. search agile
5. notice pills do not reset

**Expected behavior**
Pills should reset everytime a search has been done

** Additional Context **

IMPO i think we should be passing the filter parameters into the url to maintain state so that filters a bookmarkable. It should also make it easy to fix this bug since the url would be the single source of truth.

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary
Fixes #1245 
## Notable Changes 
- updated E2E test and verified works

### CODE REVIEW

File: app-web/src/components/Home/ResourcePreview.js [hunk 1]
```diff
@@ -84,49 +88,92 @@ export const TEST_IDS = {
...
+    const searchMap = {
+      ...queryParam,
+      [FILTER_QUERY_PARAM]: toggledFilters.length === filtersList.length ? [] : toggledFilters,
+    };
+    const searchString = queryString.stringify(searchMap);
+
     setCount(amountToShow);
+    // replacing state so that back button doesn't get poluted with filter changes
+    // also this will trigger the url to change but will not cause a page refresh unlike gatsby.navigate
+    window.history.replaceState({}, 'foo', `${pathname}?${searchString}`);
```
Comment (jas29) [inline app-web/src/components/Home/ResourcePreview.js]: Used window.replacestate instead of gatsby navigate due to auto scolling in the naviagte function

File: app-web/cypress/integration/Home/search.spec.js [hunk 2]
```diff
@@ -113,6 +116,32 @@ describe('Searching from homepage', () => {
...
+
+    cy.get('@firstFilterPill')
+      .should('have.attr', 'data-active')
+      .and('eq', 'false');
+
+    cy.log('The All pill should be automatically toggled when all the pills are selected');
+    cy.visit('?q=openshift');
+
+    cy.get('[data-testclass="resource-preview-pill"]')
+      .as('allPills')
```
Comment (patricksimonian) [inline app-web/cypress/integration/Home/search.spec.js]: no need for alias
