### PR TITLE
Make dynamic topic page client side loading

### LINKED ISSUE #1089: Incosistent rendering of Popular/Feature Topic
**Describe the bug**
The popular and feature topic appear to render inconsistently

**To Reproduce**
1. Go to https://developer.gov.bc.ca
2. Click on BackupContainer in popular topic
3. refresh page (cmd r)

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary

I found out that the dynamic topic page was not truly client side loading. This has been enabled so that page paths from `/topic/:topicType/:resource` can be parameterized. 

The reason for this change is an effort to fix the unknown css bug that affects the popular page on refresh. 

Fixes #1089

### CODE REVIEW

File: app-web/src/pages/topic.js [hunk 1]
```diff
@@ -41,7 +46,7 @@ export const TopicPage = ({ data, location }) => {
   const navigateFn = global.window ? navigate : () => null;
   const query = queryString.parse(location.search);
   const nodes = flattenGatsbyGraphQL(data.allGithubRaw.edges);
-  const [topic, topicType, resource] = location.pathname.replace(/^\/|\/$/, '').split('/');
+  // const [topic, topicType, resource] = location.pathname.replace(/^\/|\/$/, '').split('/');
```
Comment (w8896699) [inline app-web/src/pages/topic.js]: Do we want to remove comment out code?

Comment (patricksimonian) [reply app-web/src/pages/topic.js]: shoot I didn't see this
